query_type = "embedding"
automatic = true
encoder_fp = "./model/"
index = "trec-covid"

config_fn = "generic"
query_fn = "trec_covid"
parser_fn = "trec_covid"
executor_fn = "generic"

qrels = "./assets/qrels-covid_d5_j0.5-5.txt"
topics_path="./assets/topics-rdn5.xml"
