query_type = "embedding"
query_field_usage = "best_recall_fields"
embed_field_usage = "best_embed_fields"
automatic = true
encoder_fp = "./model/"
index = "clinicalcovid-bert-nli"
parser = "trec_covid"

config_fn = "generic"
query_fn = "generic"
parser_fn = "trec_covid"
executor_fn = "generic"