query_type = "embedding"
automatic = true
encoder_fp = "/home/vin/Projects/nir/outputs/submission/trec_model/"
index = "new_trec_clinical_2022"
#norm_weight = 2.5413111942656768
cosine_ceiling = 5.893593

config_fn = "generic"
query_fn = "trec_clinical"
parser_fn = "trec_clinical"
executor_fn = "generic"

qrels = "./assets/qrels2021.txt"
topics_path="./assets/topics2022.xml"